services:
  - type: web
    name: django-flower-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flowes_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Flowers_app.settings
